name: 'DA Probes'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  profiler:
    name: 'Update Probes Data'
    runs-on: ubuntu-latest
    steps:
      - name: Install pcap
        run: sudo apt-get install -y libpcap-dev

      - name: Clone Profile Data
        run: git clone https://github.com/ulixee/browser-profile-data.git
        working-directory: ..

      - name: Clone ulixee/shared
        run: git clone https://github.com/ulixee/shared.git
        working-directory: ..

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}
          submodules: 'true'

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install ulixee/shared
        run: yarn build
        working-directory: ../shared

      - name: Yarn build
        run: yarn build:simple

      - name: Import Profiles
        run: yarn workspace @ulixee/double-agent-stacks 0

      - name: Create Probes
        run: yarn workspace @ulixee/double-agent-stacks 1

      - uses: stefanzweifel/git-auto-commit-action@v5
        id: probe-data-checkin
        with:
          repository: ./double-agent/probe-data
          branch: main
          commit_message: "chore: automatic probe data"

      - uses: stefanzweifel/git-auto-commit-action@v5
        if: steps.probe-data-checkin.outputs.changes_detected == 'true'
        with:
          branch: main
          commit_message: "chore(probes): point at new double agent"
