name: 'Emulator Data'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'

jobs:
  profiler:
    name: 'Update Emulator Profile Data'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Install pcap
        run: sudo apt-get install -y libpcap-dev

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          ref: main
          submodules: 'recursive'

      - name: Clone Profile Data
        run: git clone https://github.com/ulixee/browser-profile-data.git
        working-directory: ..

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Yarn build
        run: yarn build

      - name: Yarn build
        run: yarn workspace @ulixee/unblocked-browser-emulator-builder generate

      - id: browser-data-checkin
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: browser-emulator-builder/data
          branch: main
          commit_message: 'chore(browser-emulator-builder): automatic emulator data update'

      - uses: stefanzweifel/git-auto-commit-action@v4
        if: steps.browser-data-checkin.outputs.changes_detected == 'true'
        with:
          branch: main
          commit_message: 'chore(browser-emulator-builder): automatic update emulator data ref'
