name: 'Publish a built Javascript Branch'

on:
  push:
    branches:
  workflow_dispatch:

jobs:
  build:
    name: Build Javascript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Clone ulixee/shared
        run: git clone https://github.com/ulixee/shared.git
        working-directory: ..

      - name: Install ulixee/shared
        run: yarn build
        working-directory: ../shared

      - name: Build modules
        run: yarn && yarn build:dist --network-timeout 1000000

      - name: Publish branch
        run: |
          cd build-dist
          git config --global user.email "staff@ulixee.org"
          git config --global user.name "CI"
          git init -b main
          git add -A
          git commit -m 'Auto-build Javascript files'
          git push -f https://ulixee:${{ env.GH_TOKEN }}@github.com/${{github.repository}}.git main:${{ github.ref_name }}-built-js
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
